host1 ansible_host=13.70.127.202 ansible_user=azureops
host2 ansible_host=13.70.110.106 ansible_user=azureops
host3 ansible_host=13.75.218.233 ansible_user=azureops

[web]
host2
host3

[haproxy]
host1
