---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource
      azure_rm_resourcegroup:
        name: table4msansibletest
        location: australiaeast
        tags:
          testing: testing
          delete: never
