- name: Create  VM
  hosts: localhost
  connection: local
  vars:
    group_name: table4msvmrg
    vnet: table4msVnet
    subnet: table4msSubnet
    nsgname: table4mssggroup
    nic: table4msnic
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ group_name }}"
      location: australiaeast
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ group_name }}"
      name: "{{ vnet }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ group_name }}"
      name: "{{ subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vnet }}"
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ group_name }}"
      allocation_method: Static
      name: table4msPublicIP
    register: output_ip_address
  - name: Output public IP 
    debug:
      msg: "Public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ group_name }}"
      name: "{{ nsgname }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ group_name }}"
      name: "{{ nic }}"
      virtual_network: "{{ vnet }}"
      subnet: "{{ subnet }}"
      public_ip_name: table4msPublicIP
      security_group: "{{ nsgname }}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ group_name }}"
      name: table4msVM
      vm_size: Standard_DS1_v2
      admin_username: azureops
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureops/.ssh/authorized_keys
          key_data: |
            {{ lookup('file', '/var/lib/jenkins/.ssh/id_rsa.pub')}}
      network_interfaces: "{{ nic }}"
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
